;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Buildable.cardborad",NewTagName="Buildable.cardboard")
+GameplayTagRedirects=(OldTagName="Attribute.Heath",NewTagName="Attribute.Health")
+GameplayTagList=(Tag="Attribute",DevComment="")
+GameplayTagList=(Tag="Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Buildable",DevComment="")
+GameplayTagList=(Tag="Buildable.cardboard",DevComment="")
+GameplayTagList=(Tag="Buildable.Shelf",DevComment="")

